language: java
sudo: false
install: true

jdk:
  - oraclejdk8
  - openjdk7

script:
  - mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: fab.bontemps@gmail.com
